# Generated by Django 2.0.2 on 2018-09-09 20:58

from django.db import migrations, models
import twinning_api.managers


class Migration(migrations.Migration):

    dependencies = [
        ('twinning_api', '0002_actiontoken_temporarytoken'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', twinning_api.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
