# Generated by Django 2.0.2 on 2018-09-09 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twinning_api', '0003_auto_20180909_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Organization')),
                ('logo', models.ImageField(blank=True, upload_to='organizations', verbose_name='logo')),
                ('description', models.CharField(max_length=1500, verbose_name='Description')),
                ('godson_value', models.CharField(max_length=1500, verbose_name='Godson value propositon')),
                ('godfather_value', models.CharField(max_length=1500, verbose_name='Godfather value proposition')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Country')),
                ('categories', models.ManyToManyField(blank=True, related_name='organizations', to='twinning_api.Category', verbose_name='Categories')),
                ('owners', models.ManyToManyField(related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
